const CONFIG = {
  whatsappNumber: '', // Add international digits only, e.g. 2519XXXXXXXX
  consultationEmail: 'care@tenabridge.example'
};

const translations = {
  en:{home:'Home',inbound:'Inbound',outbound:'Outbound',treatments:'Treatments',journey:'Patient Journey',hospitals:'Hospitals & Doctors',stories:'Stories',about:'About',contact:'Free Consultation',ctaIn:'Come to Ethiopia for Care',ctaOut:'Travel Abroad with Us'},
  am:{home:'መነሻ',inbound:'ወደ ኢትዮጵያ',outbound:'ወደ ውጭ ሕክምና',treatments:'ሕክምናዎች',journey:'የታካሚ ጉዞ',hospitals:'ሆስፒታሎች እና ሐኪሞች',stories:'ተሞክሮዎች',about:'ስለ እኛ',contact:'ነፃ ምክክር',ctaIn:'ለሕክምና ወደ ኢትዮጵያ ይምጡ',ctaOut:'ከእኛ ጋር ለሕክምና ይጓዙ'},
  ar:{home:'الرئيسية',inbound:'العلاج في إثيوبيا',outbound:'العلاج في الخارج',treatments:'العلاجات',journey:'رحلة المريض',hospitals:'المستشفيات والأطباء',stories:'قصص المرضى',about:'من نحن',contact:'استشارة مجانية',ctaIn:'تعال إلى إثيوبيا للعلاج',ctaOut:'سافر للعلاج معنا'},
  fr:{home:'Accueil',inbound:'Soins en Éthiopie',outbound:'Soins à l’étranger',treatments:'Traitements',journey:'Parcours patient',hospitals:'Hôpitaux & médecins',stories:'Témoignages',about:'À propos',contact:'Consultation gratuite',ctaIn:'Venir en Éthiopie',ctaOut:'Se faire soigner à l’étranger'}
};

function headerHTML(){
  const path=location.pathname.split('/').pop()||'index.html';
  const nav=[['index.html','home'],['inbound.html','inbound'],['outbound.html','outbound'],['treatments.html','treatments'],['journey.html','journey'],['hospitals.html','hospitals'],['stories.html','stories'],['about.html','about']];
  return `<header class="site-header" id="siteHeader"><div class="container nav">
    <a class="brand" href="index.html" aria-label="TenaBridge home"><span class="brand-mark"></span><span>TenaBridge<small>Medical Travel Ethiopia</small></span></a>
    <nav class="nav-links" id="navLinks" aria-label="Primary navigation">${nav.map(([href,key])=>`<a class="${path===href?'active':''}" href="${href}" data-i18n="${key}">${translations.en[key]}</a>`).join('')}</nav>
    <div class="nav-actions"><select class="lang" id="langSelect" aria-label="Language"><option value="en">EN</option><option value="am">አማ</option><option value="ar">AR</option><option value="fr">FR</option></select><a class="btn btn-primary" href="contact.html" data-i18n="contact">Free Consultation</a><button class="menu-btn" id="menuBtn" aria-label="Open menu" aria-expanded="false">☰</button></div>
  </div></header>`;
}
function footerHTML(){return `<footer class="site-footer"><div class="container"><div class="footer-grid"><div><a class="brand" href="index.html"><span class="brand-mark"></span><span>TenaBridge<small>Medical Travel Ethiopia</small></span></a><p style="max-width:390px;margin-top:18px">A patient-first bridge between Ethiopia’s healthcare ecosystem and trusted international treatment pathways. Every clinical recommendation is confirmed by the treating provider.</p></div><div><h4>Care paths</h4><div class="footer-links"><a href="inbound.html">Care in Ethiopia</a><a href="outbound.html">Care abroad</a><a href="treatments.html">Treatments</a><a href="journey.html">Patient journey</a></div></div><div><h4>Company</h4><div class="footer-links"><a href="about.html">About us</a><a href="hospitals.html">Hospitals & doctors</a><a href="stories.html">Success stories</a><a href="resources.html">Resources</a></div></div><div><h4>Contact</h4><div class="footer-links"><a href="contact.html">Free consultation</a><a href="#" class="wa-link">WhatsApp</a><a href="mailto:${CONFIG.consultationEmail}">${CONFIG.consultationEmail}</a></div></div></div><div class="footer-bottom"><p>© ${new Date().getFullYear()} TenaBridge. Medical travel coordination, not a substitute for clinical advice.</p><p>Privacy · Accessibility · Patient rights</p></div></div></footer>`}

document.addEventListener('DOMContentLoaded',()=>{
  document.body.insertAdjacentHTML('afterbegin','<a class="skip-link" href="#main">Skip to content</a>'+headerHTML());
  document.body.insertAdjacentHTML('beforeend',footerHTML()+`<a href="#" class="whatsapp wa-link" aria-label="Open WhatsApp">WA</a><div class="toast" id="toast" role="status" aria-live="polite"></div>`);
  const header=document.getElementById('siteHeader');
  addEventListener('scroll',()=>header?.classList.toggle('scrolled',scrollY>16));
  const btn=document.getElementById('menuBtn'),links=document.getElementById('navLinks');btn?.addEventListener('click',()=>{const open=links.classList.toggle('open');btn.setAttribute('aria-expanded',String(open));btn.textContent=open?'×':'☰'});
  document.querySelectorAll('.nav-links a').forEach(a=>a.addEventListener('click',()=>links?.classList.remove('open')));
  initLanguage();initReveal();initFilters();initJourney();initQuote();initMultiStep();initWhatsApp();
});

function initLanguage(){const select=document.getElementById('langSelect');const saved=localStorage.getItem('tena-lang')||'en';select.value=saved;applyLang(saved);select.addEventListener('change',e=>{localStorage.setItem('tena-lang',e.target.value);applyLang(e.target.value)});}
function applyLang(lang){const t=translations[lang]||translations.en;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;if(t[key])el.textContent=t[key]});}
function initReveal(){const els=[...document.querySelectorAll('.reveal')];if(!('IntersectionObserver'in window)){els.forEach(e=>e.classList.add('visible'));return}const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.12});els.forEach(e=>io.observe(e));}
function initFilters(){const buttons=document.querySelectorAll('.filter-btn'),items=document.querySelectorAll('.treatment-item[data-group]');buttons.forEach(b=>b.addEventListener('click',()=>{buttons.forEach(x=>x.classList.remove('active'));b.classList.add('active');const g=b.dataset.filter;items.forEach(i=>i.dataset.hidden=String(g!=='all'&&i.dataset.group!==g));}));}
function initJourney(){const steps=[...document.querySelectorAll('.journey-step[data-step]')],panel=document.getElementById('journeyPanel');if(!steps.length||!panel)return;const content={1:['Tell us what you need','Share your diagnosis, symptoms, reports, images and treatment goal. A coordinator organizes the file for clinical review.',['Secure medical-record intake','Language support','No obligation']],2:['Clinical matching & options','We identify suitable provider options based on specialty, complexity, destination preference and budget.',['Provider selection criteria','Second-opinion coordination','Clear inclusions & exclusions']],3:['Plan your travel','After a provider confirms your care plan, we coordinate visa guidance, schedule, flights, accommodation and local transport.',['Appointment schedule','Travel checklist','Airport support']],4:['Treatment & advocacy','Your coordinator stays available throughout admission, visits and discharge planning.',['Local patient support','Translation coordination','Family updates']],5:['Recovery & follow-up','We help organize discharge documents, remote follow-up and continuity with your home physician.',['Follow-up calendar','Medical document handover','Return-travel support'] ]};steps.forEach(s=>s.addEventListener('click',()=>{steps.forEach(x=>x.classList.remove('active'));s.classList.add('active');const c=content[s.dataset.step];panel.innerHTML=`<span class="eyebrow" style="color:#e0c28c">Step ${s.dataset.step}</span><h3>${c[0]}</h3><p>${c[1]}</p><div class="panel-list">${c[2].map(x=>`<div>✓ ${x}</div>`).join('')}</div>`;}));}
function initQuote(){const form=document.getElementById('quoteForm'),result=document.getElementById('quoteResult');if(!form||!result)return;form.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(form),direction=d.get('direction'),treatment=d.get('treatment'),country=d.get('country');result.innerHTML=`<strong>Planning brief created.</strong><br>${direction==='inbound'?'Care in Ethiopia':'Care abroad'} · ${treatment||'Treatment to be confirmed'}${country?` · ${country}`:''}.<br><small>Medical pricing is never guessed automatically. A verified provider estimate is prepared after clinical review.</small>`;result.classList.add('show');showToast('Your planning brief is ready.');});}
function initMultiStep(){const form=document.getElementById('consultForm');if(!form)return;let step=0;const steps=[...form.querySelectorAll('.form-step')],dots=[...form.querySelectorAll('.progress-dot')];const render=()=>{steps.forEach((s,i)=>s.classList.toggle('active',i===step));dots.forEach((d,i)=>d.classList.toggle('active',i<=step));};form.querySelectorAll('[data-next]').forEach(b=>b.addEventListener('click',()=>{const required=[...steps[step].querySelectorAll('[required]')];if(required.some(i=>!i.reportValidity()))return;step=Math.min(step+1,steps.length-1);render()}));form.querySelectorAll('[data-prev]').forEach(b=>b.addEventListener('click',()=>{step=Math.max(step-1,0);render()}));form.addEventListener('submit',e=>{e.preventDefault();showToast('Consultation request captured in this demo. Connect your CRM/email endpoint for production.');form.reset();step=0;render()});render();}
function initWhatsApp(){document.querySelectorAll('.wa-link').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();if(CONFIG.whatsappNumber){window.open(`https://wa.me/${CONFIG.whatsappNumber}?text=${encodeURIComponent('Hello TenaBridge, I would like help planning medical care.')}`,'_blank','noopener');}else{location.href='contact.html#consultation';}}));}
function showToast(msg){const t=document.getElementById('toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),3500)}
